Tamas
WDev-Beginner/mailSpammerBE pull request #2
Opened 2022-03-30 16:08 UTC by Egrishenka

2022-03-30 20:21 UTC, WDev-Beginner commented on src/main/java/com/egrine/mailspammer/emailrecipient/EmailRecipientRepository.java
> +    @Query(value="SELECT email_recipient.id, email_recipient.email_address, email_recipient.is_active, " +
extra comma

2022-03-30 20:25 UTC, WDev-Beginner requested changes
Checkout the comments on the code!

2022-03-30 20:25 UTC, WDev-Beginner commented on src/main/java/com/egrine/mailspammer/emailrecipient/implementation/InMemoryEmailRecipientService.java
> +
service layer should throw exception if the recipient is not found, you are not using the exception you defined

2022-04-05 18:06 UTC, Egrishenka commented on src/main/java/com/egrine/mailspammer/emailrecipient/implementation/InMemoryEmailRecipientService.java
> +
the exception is used in the update function, just like in the templates

2022-04-05 23:20 UTC, merged